# Inspired by https://github.com/dashbitco/nimble_parsec/blob/master/.github/workflows/ci.yml
name: Elixir CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.14.0

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: mix test
