# Inspired by https://github.com/dashbitco/nimble_parsec/blob/master/.github/workflows/ci.yml
name: Elixir CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: 1.12.1 # Define the elixir version [required]
        otp-version: 24.0.1 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
